# Site settings
title: Leadership chart
email: projects@dailycal.org
description: UC Berkeley has seen changes in half of the chancellor's cabinet — 11 top administrative positions — since April 2015.
  
baseurl: "/leadership-chart"
url: "http://projects.dailycal.org"

# Build settings
markdown: kramdown